In [ ]:

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn import base
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving datasets.csv to datasets.csv

In [ ]:
import pandas as pd
df=pd.read_csv('datasets.csv')
df

                                    Disease  ... Symptom_17
0                          Fungal infection  ...        NaN
1                                   Allergy  ...        NaN
2                                      GERD  ...        NaN
3                       Chronic cholestasis  ...        NaN
4                             Drug Reaction  ...        NaN
..                                      ...  ...        ...
63  (vertigo) Paroymsal  Positional Vertigo  ...        NaN
64                                     Acne  ...        NaN
65                  Urinary tract infection  ...        NaN
66                                Psoriasis  ...        NaN
67                                 Impetigo  ...        NaN

[68 rows x 18 columns]

In [ ]:
df_train=pd.read_csv('datasets.csv')
df_test=pd.read_csv('datasets.csv')

In [ ]:
print('train data set has got {} rows and {} columns'.format(df_train.shape[0],df_train.shape[1]))
print('test data set has got {} rows and {} columns'.format(df_test.shape[1],df_test.shape[1]))

train data set has got 68 rows and 18 columns
test data set has got 18 rows and 18 columns

In [ ]:
df_train.head()

               Disease             Symptom_1  ... Symptom_16 Symptom_17
0     Fungal infection               itching  ...        NaN        NaN
1              Allergy   continuous_sneezing  ...        NaN        NaN
2                 GERD          stomach_pain  ...        NaN        NaN
3  Chronic cholestasis               itching  ...        NaN        NaN
4        Drug Reaction               itching  ...        NaN        NaN

[5 rows x 18 columns]

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     68 non-null     object
 1   Symptom_1   68 non-null     object
 2   Symptom_2   68 non-null     object
 3   Symptom_3   68 non-null     object
 4   Symptom_4   68 non-null     object
 5   Symptom_5   60 non-null     object
 6   Symptom_6   52 non-null     object
 7   Symptom_7   47 non-null     object
 8   Symptom_8   42 non-null     object
 9   Symptom_9   36 non-null     object
 10  Symptom_10  33 non-null     object
 11  Symptom_11  24 non-null     object
 12  Symptom_12  16 non-null     object
 13  Symptom_13  11 non-null     object
 14  Symptom_14  5 non-null      object
 15  Symptom_15  4 non-null      object
 16  Symptom_16  3 non-null      object
 17  Symptom_17  1 non-null      object
dtypes: object(18)
memory usage: 9.7+ KB

In [ ]:
X=df_train.drop(['Symptom_17'],axis=1)
y=df_train['Symptom_17']

In [ ]:
features = train.columns.to_list()

In [ ]:
test = pd.read_csv("datasets.csv")
train = pd.read_csv("datasets.csv")

In [ ]:
encoder = OneHotEncoder(sparse = True, handle_unknown='ignore')
encoder.fit(train[features])
X_train = encoder.transform(train[features])
X_test = encoder.transform(test[features])

y_train = train.Symptom_17.values

print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)
print('X_test shape: ', X_test.shape)

X_train shape: (68, 163)
y_train shape: (68,)
X_test shape:  (68, 163)

In [ ]:
pd.DataFrame(X_test)

                                                    0
0     (0, 15)\t1.0\n  (0, 59)\t1.0\n  (0, 83)\t1.0...
1     (0, 4)\t1.0\n  (0, 46)\t1.0\n  (0, 82)\t1.0\...
2     (0, 16)\t1.0\n  (0, 55)\t1.0\n  (0, 60)\t1.0...
3     (0, 9)\t1.0\n  (0, 59)\t1.0\n  (0, 86)\t1.0\...
4     (0, 14)\t1.0\n  (0, 59)\t1.0\n  (0, 83)\t1.0...
..                                                ...
63    (0, 0)\t1.0\n  (0, 56)\t1.0\n  (0, 70)\t1.0\...
64    (0, 2)\t1.0\n  (0, 54)\t1.0\n  (0, 80)\t1.0\...
65    (0, 38)\t1.0\n  (0, 43)\t1.0\n  (0, 62)\t1.0...
66    (0, 35)\t1.0\n  (0, 54)\t1.0\n  (0, 73)\t1.0...
67    (0, 27)\t1.0\n  (0, 54)\t1.0\n  (0, 71)\t1.0...

[68 rows x 1 columns]

In [ ]:
df.describe(include='all')

       Disease  Symptom_1  Symptom_2  ...   Symptom_15      Symptom_16    Symptom_17
count       68         68         68  ...            4               3             1
unique      41         19         31  ...            3               3             1
top     Dengue   vomiting   vomiting  ...   chest_pain   loss_of_smell   muscle_pain
freq         5         13         14  ...            2               1             1

[4 rows x 18 columns]

In [ ]:
test.describe(include='all')

In [ ]:

### Running Count encoding on Dataset ###


df_copy = df.copy()

df_copy = df_copy.astype('str')

# Create the encoder


# Transform the features
count_encoded_all = count_enc_all.fit_transform(df_copy.iloc[:, 1:-1])
count_encoded_all = count_encoded_all/count_encoded_all.shape[0]

count_test = count_enc_all.transform(test.iloc[:,1:])

print(count_encoded_all.shape)
print(count_test.shape)

count_encoded_all.head(3)